# Generated by Django 5.1.3 on 2024-11-09 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sand",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 10, 18, 30, 30)
            ),
        ),
    ]
